#!/bin/bash

set -euo pipefail

# Load defaults, to be overwritten as desired
. ./defaults

export K8S_NODES=2
export K8S_DEPLOYMENT_ENV="prod"
export K8S_DEPLOYMENT_SCENARIO="nostn"
export IP_VERSION="ipv6"

if [ "$K8S_DEPLOYMENT_ENV" == "prod" ]; then 
    DEP_ENV="production"
else 
    DEP_ENV="development"
fi

if [ "$K8S_DEPLOYMENT_SCENARIO" == "nostn" ]; then
    DEP_SCEN="without STN"
else 
    DEP_SCEN="with STN"
fi

if [ "$IP_VERSION" == "ipv6" ] || [ "$IP_VERSION" == "ipv6transport" ] ; then
    DEP_SCEN="with $IP_VERSION"
fi

echo
echo "Creating a $DEP_ENV environment, $DEP_SCEN and $K8S_NODES worker node(s)"
echo 
./vagrant-up
